disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Austin Casteel"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Cybersecurity, Space Systems, and Culinary Craft - One Mind, Three Passions"
