colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableA11y = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
# firebase = { }
fathomAnalytics = { }
# umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }

# defaultFeaturedImage = "/img/background.jpg"
defaultBackgroundImage = "/img/background.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

mainSections = ["blog", "engprojects", ""]

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
# homepageImage = "img/background.jpg"
showRecent = true
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "/blog"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
disableHeroImageFilter = false

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = true
showWordCount = false
showZenMode = false
sharingLinks = [ "linkedin", "twitter", "whatsapp", "telegram", "pinterest", "reddit", "facebook", "email"]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
  apiKey = "AIzaSyDJujU9K2YNYQjHPl8y7AAQJP8wqgceZeI"
  authDomain = "austincasteel-website.firebaseapp.com"
  projectId = "austincasteel-website"
  storageBucket = "austincasteel-website.appspot.com"
  messagingSenderId = "420228194028"
  appId = "1:420228194028:web:a089f6a4ba7e5bf8c84fc9"
  measurementId = "G-8X093S3SP0"

[umamiAnalytics]
  websiteid = "830a6b4f-2a5d-4f5c-bd93-8ecbb36e48a6"
  enableTrackEvent = true